version: '3.8'

services:
  api:
    build: .
    container_name: zynetic-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: zynetic_db
      DB_USER: zynetic_admin
      DB_PASSWORD: zynetic_pass
      NODE_ENV: production
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: zynetic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: zynetic_db
      POSTGRES_USER: zynetic_admin
      POSTGRES_PASSWORD: zynetic_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
